# Project information
site_name: ssJSKFJDJ
site_url: https://cypress0522.github.io/ssJSKFJDJ/
site_author: 简律纯
site_description: >-
  baka!
# Repository
repo_url: https://github.com/cypress0522/ssJSKFJDJ/
repo_name: cypress0522/ssJSKFJDJ

# Copyright
copyright: Copyright &copy; 2018 - 2022 简律纯.licensed under CC BY-NC-SA 4.0.

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  favicon: assets/images/avatar.png

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  icon: 
    logo: material/Owl

# Plugins
plugins:
    - hello-dolly
    - search
    - mdoctag
    - git-revision-date
    - git-authors
    - rss
    - print-site
    - tooltips
    - categories

# Customization
extra:
  
  feedback:
      title: 这篇文章有用吗？
      ratings:
        - icon: material/heart
          name: 我很喜欢。
          data: 1
          note: >-
              你真可爱~我会更加努力的✊
        - icon: material/heart-broken
          name: 不太喜欢。
          data: 0
          note: >- 
              真是个小坏蛋，那就来 <a href="https://cypress0522.github.io/about/" target="_blank" rel="noopener">这里</a> 提交建议吧。

  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:hsiangnianian@outlook.com
    - icon: fontawesome/brands/github
      link: https://www.github.com/cypress0522

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all

  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - css/hint.min.css
# Page tree
nav:
  - Home: index.md
  - Start: 'start.md'
  - Scrpts:
    - Genshin_Impact_tts: Scripts/Genshin_Impact_tts.md
  - Module:
    - Print: Module/Print.md
  - About:
    - License: about/license.md
    - Release Notes: about/release-notes.md
  - Rss: 'Rss.md'
  - Announcement: 'Rss.md'  
  - Files:
    - Announcement: 'Files-Guide.md'
    - Scripts:
      - Guide for Scripts: 'Files-Scripts-Guide.md'
      - ranking: 'Download/Scripts/ranking.lua'
      - baseforge: 'Download/Scripts/baseforge.lua'
    - Module:
      - Guide for Module: 'Files-Module-Guide.md'
      - Print: 'Download/Module/Print.lua'
    - Print Page: './print_page/'
  - Update log:
    - Last Created: 'last-created.md'
    - Last Updated: 'last-updated.md'