# Project information
site_name: ssJSKFJDJ
site_url: https://ssjskfjdj.netlify.app/
site_author: MIZUKORA
site_description: >-
  Script & Module Recycle Bin >
# Repository
repo_url: https://github.com/ssJSKFJDJ/main-pages
repo_name: ssJSKFJDJ/main-pages

# Copyright
copyright: Copyright &copy; 2018 - 2022 ssJSKFJDJ
# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]
  features:
    - content.tooltips

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  favicon: assets/images/ico.png

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  icon: 
    logo: material/book

# Plugins
plugins:
# pip install git+https://github.com/fmaida/hello-dolly-mkdocs-plugin
  - hello-dolly
# mkdocs自带的search插件
  - search
# pip install git+https://github.com/srymh/MkdocsTagPlugin
  - mdoctag
# pip install mkdocs-git-revision-date-plugin 根据github文件信息表示最后更新时间
  - git-revision-date
# pip install mkdocs-git-authors-plugin 显示贡献者的插件
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true
# pip install mkdocs-rss-plugin
  - rss
# pip install mkdocs-print-site-plugin
  - print-site
# pip install mkdocs-izsam-video 插入本地视频，基于mkdocs-video插件
  - mkdocs-izsam-video:
      mark: "video" # ![video](./xxx.mp4)
# pip install mkdocs-tooltips 悬浮提示 []{提示}
  - tooltips
# pip install mkdocs-categories-plugin 分类插件
  - categories
# pip install mkdocs-git-show-history-log-plugin {{ git_show_history_log }}
  - git-show-history-log:
      max_number_of_commits: 3
# pip install mkdocs-video
  - mkdocs-video:
      mark: "video-2"
      is_video: True
      video_autoplay: True

# Customization
extra:
  analytics:
    provider: google
    property: UA-XXXXXXXX-X 
    feedback:
      title: 这篇文章有用吗？
      ratings:
        - icon: material/thumb-up-outline
          name: 太nm有用了，我要三连！
          data: 1
          note: >-
            你真可爱！
        - icon: material/thumb-down-outline
          name: 写的什么？
          data: 0
          note: >- 
            你tmd也太可爱了吧。
            点击<a href="https://cypress0522.github.io/about" target="_blank" rel="noopener">链接</a>来提交你的建议吧...

  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:hsiangnianian@outlook.com
    - icon: fontawesome/brands/github
      link: https://www.github.com/ssJSKFJDJ

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences

extra_css:
  - css/hint.min.css
  - css/contributors.css
# Page tree
nav:
  - Home: index.md
  - Start: 
    - Announcement: 'start.md'
    - What's New: WhatsNew.md
  # - Categories: './categories
  - Scrpts:
    - Genshin_Impact_tts.lua: Scripts/Genshin_Impact_tts.md
    - team call: Scripts/team call.md
  - Module: 
    - Print.lua: Module/Print.md
  - Wiki:
    - Midido: 
      - Guide: wiki/Midido/midido-guide.md
      - Forward: 
        - API LIST: wiki/Midido/forward.md
        - Midido: wiki/Midido/forward/Midido.md
        - Constants: wiki/Midido/forward/Constants.md
        - Util: wiki/Midido/forward/Util.md
        - ArbitraryEvent: wiki/Midido/forward/ArbitraryEvent.md
        - Chunk: wiki/Midido/forward/Chunk.md
        - MetaEvent: wiki/Midido/forward/MetaEvent.md
        - NoteEvent: wiki/Midido/forward/NoteEvent.md
        - NoteOffEvent: wiki/Midido/forward/NoteOffEvent.md
        - NoteOnEvent: wiki/Midido/forward/NoteOnEvent.md
        - PrgramChangeEvent: wiki/Midido/forward/ProgramChangeEvent.md
        - Track: wiki/Midido/forward/Track.md
        - Writer: wiki/Midido/forward/Writer.md
    - mml530:  
      - Guide: wiki/mml530/doc/mml-guide.md
      - Forward: wiki/mml530/doc/forward.md
    - gocq_api: wiki/gocq_api.md
  # - About:
  #   - License: about/license.md
  #   - Release Notes: about/release-notes.md
  - Rss:
    - Announcement: 'Rss.md'  
  - Files:
    - Announcement: 'Files-Guide.md'
    - Scripts:
      - Guide for Scripts: 'Files-Scripts-Guide.md'
    - Module:
      - Guide for Module: 'Files-Module-Guide.md'
    - Print Page: 'print_page/'
  - Updates:
    - Last Created: 'last-created.md'
    - Last Updated: 'last-updated.md'
